---
name: "go/setup"
description: |
  Sets up go and cache

inputs:
  golang-cache-enabled:
    default: "true"
    description: |
      Enable golang caching in CI
    required: false

  golang-version:
    default: "1.20"
    description: |
      Set the version for Golang
    required: false

runs:
  using: 'composite'
  steps:
  - name: Setup Go
    uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
    with:
      go-version: ${{ inputs.golang-version }}
      cache: ${{ inputs.golang-cache-enabled }}
