---
name: test
on:
  workflow_call:

jobs:
  check-style:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20.0-bullseye
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: ci/cache-gopath
      uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
      with:
        key: go-mod-v1-${{ hashFiles('go.sum') }}
        path: /go
      if: "${{ !env.ACT }}"
    - name: ci/check-code-style
      run: make check-style

  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20.0-bullseye
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      with:
        fetch-depth: 0
    - name: ci/cache-gopath
      uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
      with:
        key: go-mod-v1-${{ hashFiles('go.sum') }}
        path: /go
      if: "${{ !env.ACT }}"
    - name: ci/test
      run: make test
